"""Constants for Parser worker."""
from .config import (
    STATUS_PARSED,
    STATUS_FAILED,
    QUEUE_NAME,
    UPLOAD_SERVICE_URL_DEFAULT,
    MATCHER_ENDPOINT_PATH,
    REDIS_HOST_DEFAULT,
    REDIS_PORT_DEFAULT,
    PARSER_WORKER_CONCURRENCY_DEFAULT,
)

__all__ = [
    "STATUS_PARSED",
    "STATUS_FAILED",
    "QUEUE_NAME",
    "UPLOAD_SERVICE_URL_DEFAULT",
    "MATCHER_ENDPOINT_PATH",
    "REDIS_HOST_DEFAULT",
    "REDIS_PORT_DEFAULT",
    "PARSER_WORKER_CONCURRENCY_DEFAULT",
]
