"""Constants for Insights worker."""
from .config import (
    DEFAULT_TOP_SKILLS_LIMIT,
    STATUS_MATCHED,
    QUEUE_NAME,
    REDIS_HOST_DEFAULT,
    REDIS_PORT_DEFAULT,
    INSIGHTS_WORKER_CONCURRENCY_DEFAULT,
)

__all__ = [
    "DEFAULT_TOP_SKILLS_LIMIT",
    "STATUS_MATCHED",
    "QUEUE_NAME",
    "REDIS_HOST_DEFAULT",
    "REDIS_PORT_DEFAULT",
    "INSIGHTS_WORKER_CONCURRENCY_DEFAULT",
]
