"""Constants for OCR worker."""
from .config import (
    MIME_PDF,
    MIME_DOCX,
    MIME_TYPES_IMAGE,
    TESSERACT_CMD_DEFAULT,
    TESSERACT_LANG_DEFAULT,
    OCR_DPI,
    QUEUE_NAME,
    PARSER_QUEUE_NAME,
    REDIS_HOST_DEFAULT,
    REDIS_PORT_DEFAULT,
    OCR_WORKER_CONCURRENCY_DEFAULT,
)

__all__ = [
    "MIME_PDF",
    "MIME_DOCX",
    "MIME_TYPES_IMAGE",
    "TESSERACT_CMD_DEFAULT",
    "TESSERACT_LANG_DEFAULT",
    "OCR_DPI",
    "QUEUE_NAME",
    "PARSER_QUEUE_NAME",
    "REDIS_HOST_DEFAULT",
    "REDIS_PORT_DEFAULT",
    "OCR_WORKER_CONCURRENCY_DEFAULT",
]
